#!/bin/bash
 
function joindomain() {
	# Just in case, because we locked down the
	# sodding environment so damned much! ;-)
	PATH=$PATH:/bin:/usr/bin:/sbin:/usr/sbin

	# Get the AD controller host name
	ADHOST="$1"
	if [ -z "$ADHOST" ]; then
		echo "Syntax: $0 <adhost> <adminusername>" >&2
		exit 253
	fi

	# Get the AD admin username
	ADMINUSER="$2"
	if [ -z "$ADMINUSER" ]; then
		echo "Syntax: $0 <adhost> <adminusername>" >&2
		exit 254
	fi

	# Determine the IP address
	ADIP=`host "$ADHOST"`
	if [ "$?" -eq "0" ]; then
		ADIP=`echo "$ADIP" | awk '{print $4}'`
	else
		echo "Cannot resolve AD host '$ADHOST'; aborting!" >&2
		exit 255
	fi

	# Set the AD realm and domain
	ADREALM=`echo "$ADHOST" | cut -d'.' -f2- | tr 'a-z' 'A-Z'`
	ADDOMAIN=`echo "$ADREALM" | cut -d'.' -f1`

	echo "################# Configuration #################"
	echo "ADHOST='$ADHOST'"
	echo "ADIP='$ADIP'"
	echo "ADREALM='$ADREALM'"
	echo "ADDOMAIN='$ADDOMAIN'"
	echo "Press [Enter] to continue ..."
	read knickers

	# Install RPMs if necessary
	if	! rpm -qa samba | grep samba >/dev/null 2>&1 || \
		! rpm -qa samba-common | grep samba-common >/dev/null 2>&1 || \
		! rpm -qa samba-client | grep samba-client >/dev/null 2>&1 ; then
		yum -y install samba samba-common samba-client
	fi
	if	! rpm -qa ntp | grep ntp >/dev/null 2>&1 ; then
		yum -y install ntp
	fi
 
	# Clear away old configuration
	FILES="samba/smb.conf"
	for file in $FILES; do
		if [ -f "/etc/$file" ]; then
			mv -fv "/etc/$file" "/etc/$file.orig"
		fi
	done
 
	# Sync time against the AD host
	service ntpd stop
	cat >/etc/ntp.conf <<_EOT_
# Automagically regenerated by $0
restrict default kod nomodify notrap nopeer noquery
restrict -6 default kod nomodify notrap nopeer noquery
restrict 127.0.0.1 
restrict -6 ::1
driftfile /var/lib/ntp/drift
keys /etc/ntp/keys
server $ADIP
server 127.127.1.0
fudge	127.127.1.0 stratum 10	
_EOT_
	ntpdate $ADHOST

	# Turn on samba and winbind etc
	for service in smb winbind ntpd; do
		chkconfig $service on
		service $service restart
	done

	# Change the config
	authconfig \
		--updateall \
		--update \
		--enableshadow \
		--enablemd5 \
		--enablewinbind \
		--enablewinbindauth \
		--smbsecurity=ads \
		--smbrealm=$ADREALM \
		--smbworkgroup=$ADDOMAIN \
		--smbservers=$ADHOST \
		--winbindtemplatehomedir=/home/%U \
		--winbindtemplateshell=/bin/bash \
		--winbindjoin=$ADADMINUSER \
		--enablewinbindusedefaultdomain \
		--disablesmartcard \
		--disablerequiresmartcard \
		--enablemkhomedir \
		--enablewins \
		--enablepreferdns \
		--enablelocauthorize \
		--krb5kdc=$ADHOST \
		--krb5adminserver=$ADHOST \
		--krb5realm=$ADREALM \
		--disablenis \
		--disablekrb5 \
		--disableldap \
		--disableldapauth
		#--winbindseparator="+" \

	# Add extra stuff to samba/smb.conf
	cat >>/etc/samba/smb.conf <<_EOT_
   # Automagically added by $0
   encrypt passwords = yes
   winbind enum users = yes
   winbind enum groups = yes
   add machine script = /usr/sbin/useradd -d /var/lib/nobody -g 100 -s /bin/false -M %u
_EOT_
 
	# Force a restart on this peice of krud
	for service in smb winbind; do
		service $service stop
		sleep 1
		killall -9 ${service}d
		sleep 1
		service $service start
	done

	# Show the resulting configuration
	for file in $FILES nsswitch.conf; do
		if [ -f "/etc/$file" ]; then
			echo
			echo "################# /etc/$file #################"
			pcregrep -v "^\s*([#;].*|\s*)$" "/etc/$file"
		fi
	done

	echo
	echo "################# winbind #################"
	ps -ef | grep winbind
	echo
	 
	# Join the domain
	net join -U $ADMINUSER@$ADREALM

	# Report list of users
	echo
	wbinfo -u | tail -n 4
	wbinfo -g | tail -n 4
	getent passwd | tail -n 4
}

joindomain $*


